# Site settings
title: Shen Xu Personal Website
email: leoxushen@gmail.com
description: "Personal Webpage"
baseurl: ""
url: "http://shenxudeu.github.io"
github_username:  shenxudeu

# Build settings
#markdown: maruku
permalink: pretty
